
import com.mycompany.entregableftp1.EntregableFTP1;
import org.apache.commons.net.ftp.FTPClient;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author jacqueline
 */
public class InterfazFTP extends javax.swing.JFrame {
    
    EntregableFTP1 test = new EntregableFTP1();
    FTPClient cliente = new FTPClient();
    private String servFTP;
    private String usuario;
    private String clave;

    /**
     * Creates new form InterfazFTP
     */
    public InterfazFTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serverName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        disconect = new javax.swing.JButton();
        conect1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newPath = new javax.swing.JTextField();
        cambiar = new javax.swing.JButton();
        localPath = new javax.swing.JTextField();
        down = new javax.swing.JButton();
        up = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        servidorArea = new javax.swing.JScrollPane();
        servidorArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        comandoArea = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Remoto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel5.setText("Servidor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel1.add(serverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 30));

        jLabel6.setText("Ususario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 110, 30));

        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 130, 30));

        disconect.setLabel("Descontectar");
        disconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconectActionPerformed(evt);
            }
        });
        jPanel1.add(disconect, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        conect1.setText("Contectar");
        conect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conect1ActionPerformed(evt);
            }
        });
        jPanel1.add(conect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel2.setText("Cambiar directorio remoto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 20));
        jPanel1.add(newPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 260, 30));

        cambiar.setLabel("Cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });
        jPanel1.add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
        jPanel1.add(localPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 280, 30));

        down.setLabel("Decargar");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });
        jPanel1.add(down, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        up.setLabel("Subir");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        jLabel4.setText("Directorio local");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.setToolTipText("");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 257, 90, -1));

        servidorArea1.setColumns(20);
        servidorArea1.setRows(5);
        servidorArea.setViewportView(servidorArea1);

        jPanel1.add(servidorArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 390, 170));

        comandoArea.setBackground(new java.awt.Color(204, 204, 255));
        comandoArea.setColumns(20);
        comandoArea.setLineWrap(true);
        comandoArea.setRows(5);
        jScrollPane1.setViewportView(comandoArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 730, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconectActionPerformed
        // TODO add your handling code here:
//        test.desconectar(cliente, servFTP, usuario, clave);
        comandoArea.setText(comandoArea.getText()+" "+System.lineSeparator()+test.desconectar(cliente, servFTP, usuario, clave));
    }//GEN-LAST:event_disconectActionPerformed

    private void conect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conect1ActionPerformed
        
        String contra = "";
        char[] password = pass.getPassword();
        for (char c : password) {
            contra += c;
        }
        servFTP = serverName.getText();
        usuario = user.getText();
        clave = contra;
//        test.conectar(cliente, servFTP, usuario, clave);
        comandoArea.setText(test.conectar(cliente, servFTP, usuario, clave));
    }//GEN-LAST:event_conect1ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        // TODO add your handling code here:
//        test.cambiarDirectorio(cliente, newPath.getText());
        comandoArea.setText(comandoArea.getText()+" "+System.lineSeparator()+test.cambiarDirectorio(cliente, newPath.getText()));
        newPath.setText("");
    }//GEN-LAST:event_cambiarActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
//        test.cambiarDirectorio(cliente, "/");
        comandoArea.setText(comandoArea.getText()+" "+System.lineSeparator()+test.cambiarDirectorio(cliente, "/"));
    }//GEN-LAST:event_backActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        // TODO add your handling code here:
        test.descargar(cliente, localPath.getText());
    }//GEN-LAST:event_downActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        test.subir(cliente, localPath.getText());
    }//GEN-LAST:event_upActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        test.listar(cliente);
        servidorActionPerformed(evt);
        
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFTP().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton back;
    private javax.swing.JButton cambiar;
    private javax.swing.JTextArea comandoArea;
    private javax.swing.JButton conect1;
    private javax.swing.JButton disconect;
    private javax.swing.JButton down;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localPath;
    private javax.swing.JTextField newPath;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField serverName;
    private javax.swing.JScrollPane servidorArea;
    private javax.swing.JTextArea servidorArea1;
    private javax.swing.JButton up;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
